name: Rust Cross-Platform Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OUTPUT_PREFIX: nice
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: ${{ matrix.platform.build_name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:

          - build_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build_name: Linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build_name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - build_name: Linux-aarch64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - build_name: Linux-armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf

          - build_name: Linux-arm-musl
            os: ubuntu-latest
            target: arm-unknown-linux-musleabi

          - build_name: Linux-riscv64gc
            os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu

          - build_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - build_name: Darwin-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      
      - name: Install musl-tools on Linux
        if: contains(matrix.platform.target, 'musl')
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true
      
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
